### ISSUE TITLE
Fix for Java 8

### ISSUE THREAD

**Issue by JamoBox** [sorcix/sIRC#11]
When Travis builds with oraclejdk8 it fails.

I have fixed all but one of the errors through the JavaDoc updates, but I cannot see why this last error is being thrown. Perhaps some fresh eyes on the issue could help. Once this is fixed the project should be nice and ready for Java 8.

Travis Error:

```
[ERROR] Exit code: 1 - javadoc: warning - Error fetching URL: http://java.sun.com/javase/6/docs/api
[ERROR] /home/travis/build/JamoBox/sIRC/src/main/java/com/sorcix/sirc/IrcColors.java:49: error: unexpected text
[ERROR] * {@link "http://www.mirc.com/help/color.txt"}
[ERROR] ^
```

**Comment by sorcix** [comment]
As stated in [this answer on StackOverflow](http://stackoverflow.com/a/7341848):

> {@link} and {@linkplain} are specifically used to link to other javadoc.
> To link to a plain web page you can simply use an HTML link:
> - @see &lt;a href="http://json.org/" &gt;The JSON site&lt;/a&gt;

I guess this is the problem here. I'll fix that next weekend, thanks! :+1:
