### ISSUE TITLE
Should IrcDebug.isEnabled() be deprecated/removed?

### ISSUE THREAD

**Issue by jentfoo** [sorcix/sIRC#17]
Why would someone out of the library want to make this call?  I don't see it being used anywhere inside the library.  So I am just curious if it makes sense to keep it or not.

**Comment by sorcix** [comment]
I agree that this method has no real use case at this point. It was used before to trigger additional code inside the IrcConnection class.

However, it's just a single line getter so I don't really see a real reason to remove it.

**Comment by jentfoo** [comment]
That's fine, it's certainly not a big deal...I will go ahead and close this.
