### ISSUE TITLE
Missing IrcPacket.java?

### ISSUE THREAD

**Issue by rossjudson** [sorcix/sIRC#2]
You note in your last commit that you're redirecting traffic through IrcPacket, but I don't see it in the source tree. Perhaps it needs to be added?

**Comment by sorcix** [comment]
You're absolutely right. I've added IrcPacket.java and IrcPacketFactory.java to the repository.

**Comment by sorcix** [comment]
Has been fixed in commit 0846c85484542b4a440d1285d5ed1aad65e40bff!

**Comment by rossjudson** [comment]
Well that was fast! :)

Thanks. I've been thinking about messing around with an IRC client
that does things the way I want. I like the simplicity of what you've
set up.

RJ

On Sun, Nov 13, 2011 at 11:58 AM, sorcix
reply@reply.github.com
wrote:

> Has been fixed in commit 0846c85484542b4a440d1285d5ed1aad65e40bff!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sorcix/sIRC/issues/2#issuecomment-2723160

## 

RJ

**Comment by sorcix** [comment]
If you have any issues with it, don't hesitate to let me know!
